[package]
name = "cargo-http-registry"
version = "0.0.0"
authors = ["Daniel Mueller <deso@posteo.net>"]
edition = "2018"
license = "GPL-3.0-or-later"
homepage = "https://github.com/d-e-s-o/cargo-http-registry"
repository = "https://github.com/d-e-s-o/cargo-http-registry.git"
description = """
A cargo registry allowing for quick publishing of crates when using
crates.io is just not desired.
"""

[dependencies]
anyhow = {version = "1.0"}
git2 = {version = "0.13.12"}
http = {version = "0.2.1"}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
structopt = {version = "0.3.20"}
tokio = {version = "0.2.23", default-features = false, features = ["rt-core"]}
warp = {version = "0.2.5", default-features = false}

[dev-dependencies]
tempfile = {version = "3.1"}
