# Copyright (C) 2022-2023 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  # Build without debug information enabled to decrease compilation time
  # and binary sizes in CI. This option is assumed to only have marginal
  # effects on the generated code, likely only in terms of section
  # arrangement. See
  # https://doc.rust-lang.org/cargo/reference/environment-variables.html
  # https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo
  RUSTFLAGS: '-C debuginfo=0'

jobs:
  test:
    name: Build and test [${{ matrix.runs-on }}, ${{ matrix.rust }}, ${{ matrix.profile }}]
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
        rust: [1.60.0, stable]
        profile: [dev, release]
        include:
        - runs-on: macos-latest
          rust: stable
          profile: dev
        - runs-on: windows-latest
          rust: stable
          profile: dev
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - name: Build & test ${{ matrix.profile }}
      run: |
        git config --global user.name = "deso"
        git config --global user.email = "deso@posteo.net"
        cargo build --profile=${{ matrix.profile }} --all-targets
        cargo test --profile=${{ matrix.profile }}
  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - run: cargo clippy --no-deps --all-targets -- -A unknown_lints -A deprecated -D warnings
